import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
    # "~/.config/alacritty/themes/themes/gruvbox_light.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
decorations = "Buttonless"
opacity = 0.8
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal.family = "IosevkaTerm Nerd Font Mono"
normal.style = "Regular"
bold.family = "IosevkaTerm Nerd Font Mono"
bold.style = "Bold"
italic.family = "IosevkaTerm Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "IosevkaTerm Nerd Font Mono"
bold_italic.style = "Bold Italic"
size = 14